# Docker

# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master


resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  releaseTag: '$(Build.BuildNumber)'
  serviceName: 'forex-app'
  x86ImageName: 'emandere/$(serviceName)-x86'
  armImageName: 'emandere/$(serviceName)-arm'
  DeploymentPath: '/home/emandere/deployments/$(serviceName)/$(releaseTag)'
  GitHubDeploymentPath: 'https://raw.githubusercontent.com/emandere/$(serviceName)/master/deployment.yaml'
  DeploymentConfigPath: '/home/emandere/deployments/$(serviceName)/$(releaseTag)/deployment.yaml'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an x86 image
      inputs:
        command: buildAndPush
        repository: $(x86ImageName)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: 'dockerhub'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build an ARM image
      inputs:
        command: buildAndPush
        repository: $(armImageName)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.arm'
        containerRegistry: 'dockerhub'
        tags: |
          $(tag)