FROM emandere/forexapp-base AS builder
WORKDIR /app

COPY . ./
RUN npm install
RUN npm run build -- --output-path=/app/dist --configuration production

FROM arm64v8/nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]